// prefixes might be added in the future
const user = 'user/';
const products = 'products/';

export const LOGIN_USER = 'LOGIN_USER';
export const REGISTER_USER_START = 'REGISTER_USER_START';
export const CLEAR_REGISTER = 'CLEAR_REGISTER';
export const REGISTER_USER = 'REGISTER_USER';
export const LOGOUT_USER = 'LOGOUT_USER';

export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAILURE = 'AUTH_FAILURE';

export const GET_CART_ITEMS_USER = 'GET_CART_ITEMS_USER';
export const ADD_TO_CART_USER = 'ADD_TO_CART_USER';
export const UPDATE_CART = 'UPDATE_CART';
export const REMOVE_CART_ITEM_USER = 'REMOVE_CART_ITEM_USER';

export const ON_SUCCESS_BUY_USER = 'ON_SUCCESS_BUY_USER';
export const UPDATE_DATA_USER = 'UPDATE_DATA_USER';
export const CLEAR_UPDATE_USER_DATA = 'CLEAR_UPDATE_USER_DATA';

export const GET_PRODUCTS_BY_SELL = 'GET_PRODUCTS_BY_SELL';
export const GET_PRODUCTS_BY_ARRIVAL = 'GET_PRODUCTS_BY_ARRIVAL';
export const GET_BRANDS = 'GET_BRANDS';
export const ADD_BRAND = 'ADD_BRAND';
export const GET_WOODS =  'GET_WOODS';
export const ADD_WOOD = 'ADD_WOOD';

export const GET_PRODUCTS_TO_SHOP_START = 'GET_PRODUCTS_TO_SHOP_START';
export const GET_PRODUCTS_TO_SHOP_SUCCESS = 'GET_PRODUCTS_TO_SHOP_SUCCESS';
export const GET_PRODUCTS_TO_SHOP_FAILURE = 'GET_PRODUCTS_TO_SHOP_FAILURE';

export const ADD_PRODUCT = 'ADD_PRODUCT';
export const CLEAR_PRODUCT = 'CLEAR_PRODUCT';

export const GET_PRODUCT_DETAIL_START = 'GET_PRODUCT_DETAIL_START';
export const GET_PRODUCT_DETAIL_SUCCESS = 'GET_PRODUCT_DETAIL_SUCCESS';
export const GET_PRODUCT_DETAIL_FAILURE = 'GET_PRODUCT_DETAIL_FAILURE';

export const CLEAR_PRODUCT_DETAIL = 'CLEAR_PRODUCT_DETAIL';

export const GET_SITE_DATA = 'GET_SITE_DATA';
export const UPDATE_SITE_DATA = 'UPDATE_SITE_DATA';
